// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateManagement.Infra.Data.Data;

#nullable disable

namespace RealEstateManagement.Infra.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RealEstateManagement.Domain.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("EnergyBill")
                        .HasColumnType("double");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("TotalValue")
                        .HasColumnType("double");

                    b.Property<double>("WaterBill")
                        .HasColumnType("double");

                    b.Property<double>("WattsSpent")
                        .HasColumnType("double");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Bill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnergyBill = 150.0,
                            HouseId = 1,
                            Month = 8,
                            PaidDate = new DateTime(2023, 8, 30, 21, 5, 28, 185, DateTimeKind.Local).AddTicks(4844),
                            TotalValue = 850.0,
                            WaterBill = 50.0,
                            WattsSpent = 1000.0,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Domain.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AdressNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("BathRoomsNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<bool>("HaveGarage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HaveLaundry")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("RentValue")
                        .HasColumnType("double");

                    b.Property<int>("RoomsNumber")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("House");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Leopoldo Haerchen",
                            AdressNumber = "658",
                            BathRoomsNumber = 1,
                            City = "Blumenau",
                            Country = "Brasil",
                            District = "Badenfurt",
                            HaveGarage = true,
                            HaveLaundry = true,
                            RentValue = 650.0,
                            RoomsNumber = 2,
                            State = "Santa Catarina",
                            ZipCode = "89072040"
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationCard")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Email = "patrick@gmail.com",
                            HouseId = 1,
                            IdentificationCard = "06262485902",
                            Name = "Patrick",
                            PhoneNumber = "47989098585"
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Domain.Models.Bill", b =>
                {
                    b.HasOne("RealEstateManagement.Domain.Models.House", "House")
                        .WithMany("Bills")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("RealEstateManagement.Domain.Models.Person", b =>
                {
                    b.HasOne("RealEstateManagement.Domain.Models.House", "House")
                        .WithMany("People")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("RealEstateManagement.Domain.Models.House", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
